# Generated by Django 3.2.4 on 2021-06-29 12:37

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phone_field.models.PhoneField(max_length=10, unique=True),
        ),
    ]
